### ISSUE TITLE
Revisit README.md documents in all active repositories

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/.github#5]
#### Todos for each repo

* Make them look nice
  * Header
    * Have the Circles logo on top, centered, next or above the repository title
    * Upload the `logo.svg` asset into `.github` repo
    * Short sentence describing what this code is about
    * Badges (use https://shields.io)
      * Update CI test badge
      * For Published npm packages: Version
      * Discourse
      * Twitter
    * Main links
      * API Docs (Generated via CI and hosted on GH pages)
      * Handbook
      * Releases (from GitHub) / aka. Changelog
      *Contributing (Contributing guidelines document)
* When existing, move `API.md` into separate files (keep it short!)

#### List of active repos in Circles UBI

* [x] circles-myxogastria (https://github.com/CirclesUBI/circles-myxogastria/pull/162)
* [x] circles-contracts (https://github.com/CirclesUBI/circles-contracts/pull/122)
* [x] circles-api (https://github.com/CirclesUBI/circles-api/pull/51)
* [x] circles-core (https://github.com/CirclesUBI/circles-core/pull/70)
* [x] circles-docker (https://github.com/CirclesUBI/circles-docker/pull/30)
* [x] safe-relay-service (https://github.com/CirclesUBI/safe-relay-service/pull/41)
* [x] circles-website
* [x] circles-dashboard (https://github.com/CirclesUBI/circles-dashboard/pull/9)
* [x] circles-handbook (https://github.com/CirclesUBI/circles-handbook/pull/6)
* [x] circles-subgraph (https://github.com/CirclesUBI/circles-subgraph/pull/36)
* [x] circles-transfer (https://github.com/CirclesUBI/circles-transfer/pull/7)
* [x] circles-iac (https://github.com/CirclesUBI/circles-iac/pull/7)
* [x] whitepaper

**Comment by louilinn** [comment]
I will wait with this until we have finished contributing guidelines and code of conduct, or at least have a place / link for them.

@adz Regarding the support channels, we were moving to rocket chat right so also pending that? Or which channels make sense to link?

**Comment by adz** [comment]
I think you pinged the wrong adz 😁 @louilinn

**Comment by adzialocha** [comment]
> @adzialocha Regarding the support channels, we were moving to rocket chat right so also pending that? Or which channels make sense to link?

The chat discussion is still pending (either https://chat.joincircles.net or a new discourse channel) but we can already link to https://aboutcircles.com (SSL is currently broken, but I'm on it!).

> Also, just making sure, should I go through all the non-archived repos as listed in the description comment?

Yes this looks good. I sorted them by priority so we can start with the most important ones.

**Comment by louilinn** [comment]
@adzialocha The subgraph repo has an open collective badge in its README.md Do we want to keep this or even add add it to more repos?

**Comment by adzialocha** [comment]
> @adzialocha The subgraph repo has an open collective badge in its README.md Do we want to keep this or even add add it to more repos?
> 

I think the Circles team wanted to close this account, so let's remove it 👍

**Comment by louilinn** [comment]
Hey, I created PRs for the last two repos. I assume we should not do whitepaper and website or?
